Attribute VB_Name = "Global"
Declare Function sndPlaySound Lib "winmm.dll" Alias "sndPlaySoundA" (ByVal lpszSoundName As String, ByVal uFlags As Long) As Long
Global Const SND_SYNC = &H0
   Global Const SND_ASYNC = &H1
   Global Const SND_NODEFAULT = &H2
   Global Const SND_LOOP = &H8
   Global Const SND_NOSTOP = &H10
Global percentagerate As String
Global hopper2 As Double
Global giveme As Integer
Global previousgame As Integer
Global bettotal As Double
Global warningshown As Integer
Global hopperempty As Double
Global lastcredits As Double
Global soundonoff As Integer
Global delaytime As Long
Global key As Double
Global key2 As Double
Global amountbet As Integer
Global boxes_checked As Integer
Global dollars As Double
Global c1_checked As Single
Global c2_checked As Single
Global c3_checked As Single
Global c4_checked As Single
Global c5_checked As Single
Global c6_checked As Single
Global c7_checked As Single
Global c8_checked As Single
Global c9_checked As Single
Global c10_checked As Single
Global c11_checked As Single
Global c12_checked As Single
Global c13_checked As Single
Global c14_checked As Single
Global c15_checked As Single
Global c16_checked As Single
Global c17_checked As Single
Global c18_checked As Single
Global c19_checked As Single
Global c20_checked As Single
Global c21_checked As Single
Global c22_checked As Single
Global c23_checked As Single
Global c24_checked As Single
Global c25_checked As Single
Global c26_checked As Single
Global c27_checked As Single
Global c28_checked As Single
Global c29_checked As Single
Global c30_checked As Single
Global c31_checked As Single
Global c32_checked As Single
Global c33_checked As Single
Global c34_checked As Single
Global c35_checked As Single
Global c36_checked As Single
Global c37_checked As Single
Global c38_checked As Single
Global c39_checked As Single
Global c40_checked As Single
Global c41_checked As Single
Global c42_checked As Single
Global c43_checked As Single
Global c44_checked As Single
Global c45_checked As Single
Global c46_checked As Single
Global c47_checked As Single
Global c48_checked As Single
Global c49_checked As Single
Global c50_checked As Single
Global c51_checked As Single
Global c52_checked As Single
Global c53_checked As Single
Global c54_checked As Single
Global c55_checked As Single
Global c56_checked As Single
Global c57_checked As Single
Global c58_checked As Single
Global c59_checked As Single
Global c60_checked As Single
Global c61_checked As Single
Global c62_checked As Single
Global c63_checked As Single
Global c64_checked As Single
Global c65_checked As Single
Global c66_checked As Single
Global c67_checked As Single
Global c68_checked As Single
Global c69_checked As Single
Global c70_checked As Single
Global c71_checked As Single
Global c72_checked As Single
Global c73_checked As Single
Global c74_checked As Single
Global c75_checked As Single
Global c76_checked As Single
Global c77_checked As Single
Global c78_checked As Single
Global c79_checked As Single
Global c80_checked As Single
Global totaldeals As Double
Global dealt As Integer
Global hits As Integer
Global getgame As Integer
Global playersname As String
Global autoplay As Double
Global autokenomode As Integer
Global keys As Integer
Global normalwidth As Single
Global normalheight As Single
Global fullmode As Integer
Global autostop As Integer
