VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsArmor"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'this class represents an Armor
Dim itsIDNum As Integer
Dim itsName As String
Dim itsDesc As String
Dim itsAC As Integer
Dim itsMPPlus As Integer
Dim itsHPPlus As Integer
Dim itsINTPlus As Integer
Dim itsSTAPlus As Integer
Dim itsSTRPlus As Integer
Dim itsMeleeDamPlus As Integer
Dim itsPiercingDamPlus As Integer
Dim itsWeight As Integer


