PIC.FRM
..\THREED.VBX
..\VBPROJ\VBMSG.VBX
PARANOID.BAS
INIFILE.BAS
..\VBPROJ\CMDIALOG.VBX
MMER.FRM
MMOPTION.FRM
MMSTATUS.FRM
PWAIT.FRM
MMBOTFRM.FRM
ROOMFIND.FRM
ROOMBUST.FRM
ProjWinSize=522,3,192,215
ProjWinShow=2
IconForm="MMerFrm"
Title="UPSS Mass Mailer"
ExeName="UPSSMM.EXE"
