Attribute VB_Name = "ModChnge"
Public Sub UpdateSettings()
On Error Resume Next
FrmExmp1.Height = GetSetting(App.Path & "\Settings.ini", "thing", "frmHieght")
FrmExmp1.Width = GetSetting(App.Path & "\Settings.ini", "thing", "frmWidth")
FrmExmp1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "FrmBG")
FrmExmp1.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "FrmFont")
FrmExmp1.OptMove.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "OptBG")
FrmExmp1.OptMove.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "OptFont")
FrmExmp1.OptMove.Left = GetSetting(App.Path & "\Settings.ini", "thing", "OptLeft")
FrmExmp1.OptMove.Top = GetSetting(App.Path & "\Settings.ini", "thing", "OptTop")
FrmExmp1.TxtExmp1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "TxtBG")
FrmExmp1.TxtExmp1.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "TxtFont")
FrmExmp1.TxtExmp1.Left = GetSetting(App.Path & "\Settings.ini", "thing", "TxtLeft")
FrmExmp1.TxtExmp1.Top = GetSetting(App.Path & "\Settings.ini", "thing", "TxtTop")
FrmExmp1.Command1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "cmdBG")
FrmExmp1.Command1.Left = GetSetting(App.Path & "\Settings.ini", "thing", "CmdLeft")
FrmExmp1.Command1.Top = GetSetting(App.Path & "\Settings.ini", "thing", "CmdTop")
FrmExmp1.List1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "lstBG")
FrmExmp1.List1.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "lstFont")
FrmExmp1.List1.Left = GetSetting(App.Path & "\Settings.ini", "thing", "LstLeft")
FrmExmp1.List1.Top = GetSetting(App.Path & "\Settings.ini", "thing", "LstTop")
End Sub

Public Sub UpSett()
On Error Resume Next
FrmMove1.Height = GetSetting(App.Path & "\Settings.ini", "thing", "frmHieght")
FrmMove1.Width = GetSetting(App.Path & "\Settings.ini", "thing", "frmWidth")
FrmMove1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "FrmBG")
FrmMove1.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "FrmFont")
FrmMove1.OptMove.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "OptBG")
FrmMove1.OptMove.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "OptFont")
FrmMove1.OptMove.Left = GetSetting(App.Path & "\Settings.ini", "thing", "OptLeft")
FrmMove1.OptMove.Top = GetSetting(App.Path & "\Settings.ini", "thing", "OptTop")
FrmMove1.TxtExmp1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "TxtBG")
FrmMove1.TxtExmp1.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "TxtFont")
FrmMove1.TxtExmp1.Left = GetSetting(App.Path & "\Settings.ini", "thing", "TxtLeft")
FrmMove1.TxtExmp1.Top = GetSetting(App.Path & "\Settings.ini", "thing", "TxtTop")
FrmMove1.Command1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "cmdBG")
FrmMove1.Command1.Left = GetSetting(App.Path & "\Settings.ini", "thing", "CmdLeft")
FrmMove1.Command1.Top = GetSetting(App.Path & "\Settings.ini", "thing", "CmdTop")
FrmMove1.List1.BackColor = GetSetting(App.Path & "\Settings.ini", "thing", "lstBG")
FrmMove1.List1.ForeColor = GetSetting(App.Path & "\Settings.ini", "thing", "lstFont")
FrmMove1.List1.Left = GetSetting(App.Path & "\Settings.ini", "thing", "LstLeft")
FrmMove1.List1.Top = GetSetting(App.Path & "\Settings.ini", "thing", "LstTop")
End Sub

Public Sub SaveSett()
Call SaveSetting(App.Path & "\Settings.ini", "thing", "frmHieght", FrmMove1.Height)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "frmWidth", FrmMove1.Width)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "FrmBG", FrmMove1.BackColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "FrmFont", FrmMove1.ForeColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "OptBG", FrmMove1.OptMove.BackColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "OptFont", FrmMove1.OptMove.ForeColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "OptLeft", FrmMove1.OptMove.Left)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "OptTop", FrmMove1.OptMove.Top)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "TxtBG", FrmMove1.TxtExmp1.BackColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "TxtFont", FrmMove1.TxtExmp1.ForeColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "TxtLeft", FrmMove1.TxtExmp1.Left)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "TxtTop", FrmMove1.TxtExmp1.Top)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "cmdBG", FrmMove1.Command1.BackColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "CmdLeft", FrmMove1.Command1.Left)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "CmdTop", FrmMove1.Command1.Top)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "lstBG", FrmMove1.List1.BackColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "lstFont", FrmMove1.List1.ForeColor)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "LstLeft", FrmMove1.List1.Left)
Call SaveSetting(App.Path & "\Settings.ini", "thing", "LstTop", FrmMove1.List1.Top)
End Sub
