Attribute VB_Name = "LDAPConstants"
'========================================================================
' Copyright 1999 - Digital Press, John Rhoton
'
' This program has been written to illustrate the Internet Mail protocols.
' It is provided free of charge and unconditionally.  However, it is not
' intended for production use, and therefore without warranty or any
' implication of support.
'
' You can find an explanation of the concepts behind this code in
' the book:  Programmer's Guide to Internet Mail by John Rhoton,
' Digital Press 1999.  ISBN: 1-55558-212-5.
'
' For ordering information please see http://www.amazon.com or
' you can order directly with http://www.bh.com/digitalpress.
'
'========================================================================

Public Const LDAP_FALSE = 0
Public Const LDAP_TRUE = 1

Public Const LDAP_BINDREQUEST_TAG = 0 + ASN_APPLICATION + ASN_COMPOSITE ' 96
Public Const LDAP_BINDRESPONSE_TAG = 1 + ASN_APPLICATION + ASN_COMPOSITE ' 97
Public Const LDAP_UNBINDREQUEST_TAG = 2 + ASN_APPLICATION + ASN_COMPOSITE '98
Public Const LDAP_SEARCHREQUEST_TAG = 3 + ASN_APPLICATION + ASN_COMPOSITE '99
Public Const LDAP_SEARCHRESPONSEENTRY_TAG = 4 + ASN_APPLICATION + ASN_COMPOSITE ' 100
Public Const LDAP_SEARCHRESPONSERESULT_TAG = 5 + ASN_APPLICATION + ASN_COMPOSITE '101
Public Const LDAP_ABANDONREQUEST_TAG = 16 + ASN_APPLICATION + ASN_COMPOSITE ' 112

Public Const LDAP_SEARCH_AND = 0 + ASN_CONTEXT_SPECIFIC + ASN_COMPOSITE  ' 160
Public Const LDAP_SEARCH_OR = 1 + ASN_CONTEXT_SPECIFIC + ASN_COMPOSITE   ' 161
Public Const LDAP_SEARCH_NOT = 2 + ASN_CONTEXT_SPECIFIC    '
Public Const LDAP_SEARCH_EQUALITYMATCH = 3 + ASN_CONTEXT_SPECIFIC   '
Public Const LDAP_SEARCH_SUBSTRINGS = 4 + ASN_CONTEXT_SPECIFIC + ASN_COMPOSITE   '

Public Const LDAP_SUBSTRING_INITIAL = 0 + ASN_CONTEXT_SPECIFIC
Public Const LDAP_SUBSTRING_ANY = 1 + ASN_CONTEXT_SPECIFIC
Public Const LDAP_SUBSTRING_FINAL = 2 + ASN_CONTEXT_SPECIFIC

Public Const LDAP_AUTHENTICATION_SIMPLE = 0
Public Const LDAP_AUTHENTICATION_KRBV42LDAP = 1
Public Const LDAP_AUTHENTICATION_KRBV42DSA = 2

Public Const LDAP_SCOPE_BASEOBJECT = 0
Public Const LDAP_SCOPE_SINGLELEVEL = 1
Public Const LDAP_SCOPE_WHOLESUBTREE = 2

Public Const LDAP_DEREFALIASES_NEVER = 0
Public Const LDAP_DEREFALIASES_INSEARCHING = 1
Public Const LDAP_DEREFALIASES_FINDINGBASEOBJ = 2
Public Const LDAP_DEREFALIASES_ALWAYS = 3

Public Const LDAP_RESULT_SUCCESS = 0
Public Const LDAP_RESULT_OPERATIONSERROR = 1
Public Const LDAP_RESULT_PROTOCOLERROR = 2
Public Const LDAP_RESULT_TIMELIMITEXCEEDED = 3
Public Const LDAP_RESULT_SIZELIMITEXCEEDED = 4
Public Const LDAP_RESULT_COMPAREFALSE = 5
Public Const LDAP_RESULT_COMPARETRUE = 6
Public Const LDAP_RESULT_AUTHMETHODNOTSUPPORTED = 7
Public Const LDAP_RESULT_STRONGAUTHREQUIRED = 8
Public Const LDAP_RESULT_NOSUCHATTRIBUTE = 16
Public Const LDAP_RESULT_UNDEFINEDATTRIBUTETYPE = 17
Public Const LDAP_RESULT_INAPPROPRIATEMATCHING = 18
Public Const LDAP_RESULT_CONSTRAINTVIOLATION = 19
Public Const LDAP_RESULT_ATTRIBUTEORVALUEEXISTS = 20
Public Const LDAP_RESULT_INVALIDATTRIBUTESYNTAX = 21
Public Const LDAP_RESULT_NOSUCHOBJECT = 32
Public Const LDAP_RESULT_ALIASPROBLEM = 33
Public Const LDAP_RESULT_INVALIDDNSYNTAX = 34
Public Const LDAP_RESULT_ISLEAF = 35
Public Const LDAP_RESULT_ALIASDEREFERENCINGPROBLEM = 36
Public Const LDAP_RESULT_INAPPROPRIATEAUTHENTICATION = 48
Public Const LDAP_RESULT_INVALIDCREDENTIALS = 49
Public Const LDAP_RESULT_INSUFFICIENTACCESSRIGHTS = 50
Public Const LDAP_RESULT_BUSY = 51
Public Const LDAP_RESULT_UNAVAILABLE = 52
Public Const LDAP_RESULT_UNWILLINGTOPERFORM = 53
Public Const LDAP_RESULT_LOOPDETECT = 54
Public Const LDAP_RESULT_NAMINGVIOLATION = 64
Public Const LDAP_RESULT_OBJECTCLASSVIOLATION = 65
Public Const LDAP_RESULT_NOTALLOWEDONNONLEAF = 66
Public Const LDAP_RESULT_NOTALLOWEDONRDN = 67
Public Const LDAP_RESULT_ENTRYALREADYEXISTS = 68
Public Const LDAP_RESULT_OBJECTCLASSMODSPROHIBITED = 69
Public Const LDAP_RESULT_OTHER = 80
