VERSION 2.00
Begin Form frmChild 
   Caption         =   "Form1"
   ClientHeight    =   2280
   ClientLeft      =   2535
   ClientTop       =   3255
   ClientWidth     =   4335
   Height          =   2685
   Left            =   2475
   LinkTopic       =   "Form1"
   MDIChild        =   -1  'True
   ScaleHeight     =   2280
   ScaleWidth      =   4335
   Top             =   2910
   Width           =   4455
End
Option Explicit

