VERSION 4.00
Begin VB.Form Form2 
   Caption         =   "Form2"
   ClientHeight    =   150
   ClientLeft      =   3525
   ClientTop       =   3885
   ClientWidth     =   6690
   Height          =   555
   Left            =   3465
   LinkTopic       =   "Form2"
   ScaleHeight     =   150
   ScaleWidth      =   6690
   Top             =   3540
   Width           =   6810
End
Attribute VB_Name = "Form2"
Attribute VB_Creatable = False
Attribute VB_Exposed = False
