VERSION 2.00
Begin Form Fakes 
   BackColor       =   &H00C0C0C0&
   BorderStyle     =   3  'Fixed Double
   Caption         =   "Phake Maker"
   ClientHeight    =   3615
   ClientLeft      =   5235
   ClientTop       =   705
   ClientWidth     =   3615
   Height          =   4020
   Icon            =   FAKES.FRX:0000
   Left            =   5175
   LinkTopic       =   "Form1"
   MaxButton       =   0   'False
   MinButton       =   0   'False
   ScaleHeight     =   3615
   ScaleWidth      =   3615
   Top             =   360
   Width           =   3735
   Begin SSPanel Panel3D2 
      BevelInner      =   1  'Inset
      ForeColor       =   &H00000000&
      Height          =   3615
      Left            =   0
      ShadowColor     =   1  'Black
      TabIndex        =   10
      Top             =   0
      Width           =   3615
      Begin SSPanel Panel3D3 
         BevelInner      =   1  'Inset
         BevelOuter      =   1  'Inset
         Caption         =   "BaKa"
         FontBold        =   -1  'True
         FontItalic      =   0   'False
         FontName        =   "Arial"
         FontSize        =   13.5
         FontStrikethru  =   0   'False
         FontUnderline   =   0   'False
         ForeColor       =   &H00FF0000&
         Height          =   495
         Left            =   2280
         ShadowColor     =   1  'Black
         TabIndex        =   0
         Top             =   3000
         Width           =   1215
      End
      Begin SSFrame Frame3D1 
         Caption         =   "Registration Information"
         FontBold        =   -1  'True
         FontItalic      =   0   'False
         FontName        =   "Arial"
         FontSize        =   8.25
         FontStrikethru  =   0   'False
         FontUnderline   =   0   'False
         Height          =   2775
         Left            =   120
         ShadowColor     =   1  'Black
         ShadowStyle     =   1  'Raised
         TabIndex        =   14
         Top             =   120
         Width           =   3375
         Begin TextBox Text12 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   1920
            TabIndex        =   26
            Top             =   2400
            Width           =   1335
         End
         Begin TextBox Text11 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   480
            TabIndex        =   25
            Top             =   2400
            Width           =   1335
         End
         Begin TextBox Text10 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   600
            TabIndex        =   24
            Top             =   960
            Width           =   1575
         End
         Begin TextBox Text9 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   480
            MaxLength       =   5
            TabIndex        =   23
            Top             =   1320
            Width           =   615
         End
         Begin TextBox Text8 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   2640
            MaxLength       =   5
            TabIndex        =   22
            Top             =   1680
            Width           =   615
         End
         Begin TextBox Text7 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   600
            TabIndex        =   21
            Top             =   2040
            Width           =   2655
         End
         Begin TextBox Text6 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   480
            MaxLength       =   19
            TabIndex        =   20
            Top             =   1680
            Width           =   2055
         End
         Begin TextBox Text5 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   2880
            MaxLength       =   2
            TabIndex        =   19
            Top             =   960
            Width           =   375
         End
         Begin TextBox Text4 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   1800
            MaxLength       =   12
            TabIndex        =   18
            Top             =   1320
            Width           =   1455
         End
         Begin TextBox Text3 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   960
            TabIndex        =   17
            Top             =   600
            Width           =   2295
         End
         Begin TextBox Text2 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   2040
            TabIndex        =   16
            Top             =   240
            Width           =   1215
         End
         Begin TextBox Text1 
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Courier New"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   315
            Left            =   720
            TabIndex        =   15
            Top             =   240
            Width           =   1215
         End
         Begin Label Label6 
            BackStyle       =   0  'Transparent
            Caption         =   "Reg:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   1
            Top             =   2400
            Width           =   495
         End
         Begin Label Label9 
            BackStyle       =   0  'Transparent
            Caption         =   "Name:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   2
            Top             =   240
            Width           =   975
         End
         Begin Label Label8 
            BackStyle       =   0  'Transparent
            Caption         =   "Bank:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   3
            Top             =   2040
            Width           =   735
         End
         Begin Label Label7 
            BackStyle       =   0  'Transparent
            Caption         =   "Zip:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   4
            Top             =   1320
            Width           =   735
         End
         Begin Label Label5 
            BackStyle       =   0  'Transparent
            Caption         =   "State:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   2280
            TabIndex        =   5
            Top             =   960
            Width           =   735
         End
         Begin Label Label4 
            BackStyle       =   0  'Transparent
            Caption         =   "City:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   6
            Top             =   960
            Width           =   375
         End
         Begin Label Label3 
            BackStyle       =   0  'Transparent
            Caption         =   "CC:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   7
            Top             =   1680
            Width           =   495
         End
         Begin Label Label2 
            BackStyle       =   0  'Transparent
            Caption         =   "Address:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   120
            TabIndex        =   8
            Top             =   600
            Width           =   1695
         End
         Begin Label Label1 
            BackStyle       =   0  'Transparent
            Caption         =   "Phone:"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            Height          =   255
            Left            =   1200
            TabIndex        =   9
            Top             =   1320
            Width           =   735
         End
      End
      Begin SSPanel Panel3D1 
         BevelInner      =   2  'Raised
         BevelOuter      =   1  'Inset
         FontBold        =   -1  'True
         FontItalic      =   0   'False
         FontName        =   "Arial"
         FontSize        =   8.25
         FontStrikethru  =   0   'False
         FontUnderline   =   0   'False
         ForeColor       =   &H00000000&
         Height          =   495
         Left            =   120
         ShadowColor     =   1  'Black
         TabIndex        =   11
         Top             =   3000
         Width           =   2055
         Begin SSCommand Command3D2 
            Caption         =   "Begin"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            ForeColor       =   &H00000000&
            Height          =   255
            Left            =   1200
            RoundedCorners  =   0   'False
            TabIndex        =   13
            Top             =   120
            Width           =   735
         End
         Begin SSCommand Command3D1 
            Caption         =   "Generate"
            FontBold        =   -1  'True
            FontItalic      =   0   'False
            FontName        =   "Arial"
            FontSize        =   8.25
            FontStrikethru  =   0   'False
            FontUnderline   =   0   'False
            ForeColor       =   &H00000000&
            Height          =   255
            Left            =   120
            RoundedCorners  =   0   'False
            TabIndex        =   12
            Top             =   120
            Width           =   975
         End
      End
   End
End
' FAKES.FRM
Option Explicit
Const c0208 =-1 ' &HFFFF%
Const c020A = 3 ' &H3%

Sub Command3D1_Click ()
Dim l001A As Variant
Dim l0024 As Variant
Dim l0028 As Variant
Dim l002C As Variant
Dim l0030 As Variant
Dim l0034 As Variant
Dim l004A As Variant
Dim l004E As Variant
Dim l0052 As Variant
Dim l0056 As Variant
Dim l0060 As Variant
Dim l0064 As Variant
Dim l0068 As Variant
Dim l006C As Variant
Dim l0070 As Variant
Dim l0074 As Variant
Dim l0078 As Variant
Dim l0082 As Variant
Dim l008C As Variant
Dim l00A2 As Variant
Dim l00A6 As Variant
Dim l00AA As Variant
Static m00AE(16) As Variant
Dim l00C4 As Variant
Dim l00C8 As Variant
Dim l00CC As Variant
Dim l00D0 As Variant
Dim l00D4 As Variant
Dim l00D8 As Variant
Dim l00DC As Variant
Dim l00E0 As Variant
Dim l00E4 As Variant
Dim l00E8 As Variant
Dim l00EC As Variant
Dim l00F0 As Variant
Dim l00F4 As Variant
Dim l00F8 As Variant
Dim l00FC As Variant
Dim l0100 As Variant
Dim l0104 As Variant
Dim l0108 As Variant
Dim l010C As Variant
Dim l0110 As Variant
Dim l0114 As Variant
Dim l0118 As Variant
Dim l011C As Variant
Dim l0120 As Variant
Dim l0124 As Variant
Dim l0128 As Variant
Dim l012C As Variant
Dim l0130 As Variant
Dim l0134 As Variant
Dim l0138 As Variant
Dim l013C As Variant
Dim l0140 As Variant
Dim l0144 As Variant
Dim l0148 As Variant
Dim l014C As Variant
Dim l0150 As Variant
Dim l0154 As Variant
Dim l0158 As Variant
Dim l015C As Variant
Dim l0160 As Variant
Dim l0164 As Variant
Dim l0168 As Variant
Dim l016C As Variant
Dim l0170 As Variant
Dim l0174 As Variant
Dim l0178 As Variant
Dim l017C As Variant
Dim l0180 As Variant
Dim l0184 As Variant
Dim l0188 As Variant
Dim l018C As Variant
Dim l0190 As Variant
Dim l0194 As Variant
Dim l0198 As Variant
Dim l019C As Variant
Randomize
l001A = Int(Rnd * 12)
If  l001A = 0 Then l001A = 12
If  l001A > 9 Then Text8.Text = Right$(Str$(l001A), 2) & "-98" Else Text8.Text = "0" & Right$(Str$(l001A), 1) & "-97"
l0024 = Int(Rnd * 10)
Select Case l0024
Case 0: l0028 = "Jefferson City": l002C = "MO": l0030 = "65106": l0034 = "314-425-"
Case 1: l0028 = "Frankfort": l002C = "KY": l0030 = "40601": l0034 = "502-699-"
Case 2: l0028 = "Tallahassee": l002C = "FL": l0030 = "32303": l0034 = "904-476-"
Case 3: l0028 = "Pierre": l002C = "SD": l0030 = "57501": l0034 = "605-561-"
Case 4: l0028 = "Frankfort": l002C = "KY": l0030 = "40601": l0034 = "502-699-"
Case 5: l0028 = "Concord": l002C = "NH": l0030 = "03301": l0034 = "603-866-"
Case 6: l0028 = "Springfield": l002C = "MA": l0030 = "01101": l0034 = "413-849-"
Case 7: l0028 = "Montpelier": l002C = "VT": l0030 = "05602": l0034 = "802-496-"
Case 8: l0028 = "Salt Lake City": l002C = "UT": l0030 = "84122": l0034 = "801-810-"
Case 9: l0028 = "Detroit": l002C = "MI": l0030 = "48200": l0034 = "313-614-"
Case 10: l0028 = "Milwaukee": l002C = "WI": l0030 = "53209": l0034 = "414-864-"
End Select
Text10.Text = l0028
Text5.Text = l002C
Text9.Text = l0030
l004A = Int(Rnd * 9)
l004E = Int(Rnd * 9)
l0052 = Int(Rnd * 9)
l0056 = Int(Rnd * 9)
Text4.Text = l0034 & Right$(Str$(l004A), 1) & Right$(Str$(l004E), 1) & Right$(Str$(l0052), 1) & Right$(Str$(l0056), 1)
l0060 = Int(Rnd * 9)
l0064 = Int(Rnd * 9)
l0068 = Int(Rnd * 9)
l006C = Int(Rnd * 9)
l0070 = Int(Rnd * 35)
Select Case l0070
Case 0: l0074 = "E Gilbert"
Case 1: l0074 = "N Woodrow"
Case 2: l0074 = "S Market"
Case 3: l0074 = "W 13th St"
Case 4: l0074 = "W Crocus Ave"
Case 5: l0074 = "S Panacea Ln"
Case 6: l0074 = "N Oak Blvd"
Case 7: l0074 = "E Meredith"
Case 8: l0074 = "S Seneca"
Case 9: l0074 = "E Kellog"
Case 10: l0074 = "N Rock Rd"
Case 11: l0074 = "S Lockimvar"
Case 12: l0074 = "S Broadway"
Case 13: l0074 = "Layafette"
Case 14: l0074 = "N Woodland"
Case 15: l0074 = "Wire Ln"
Case 16: l0074 = "Cedarwood Ct"
Case 17: l0074 = "S Battin"
Case 18: l0074 = "E Roseberry"
Case 19: l0074 = "S Bonn"
Case 20: l0074 = "N Dunsworth"
Case 21: l0074 = "S Larkin"
Case 22: l0074 = "N Miles Ave"
Case 23: l0074 = "S Clifton"
Case 24: l0074 = "Hammond"
Case 25: l0074 = "N Pinecrest"
Case 26: l0074 = "W Oak St"
Case 27: l0074 = "N Rover Ln"
Case 28: l0074 = "Washington Blvd"
Case 29: l0074 = "N Manhatten"
Case 30: l0074 = "E 27th St"
Case 31: l0074 = "W 11th St"
Case 32: l0074 = "E 29th St"
Case 33: l0074 = "Spaulding St"
Case 34: l0074 = "Mallard Ave"
Case 35: l0074 = "W Petersdale Rd"
End Select
If  l0060 = 0 Then l0078 = "" Else l0078 = Right$(Str$(l0060), 1)
If  l0060 = 0 And l0064 = 0 Then l0064 = 4
Text3.Text = l0078 & Right$(Str$(l0064), 1) & Right$(Str$(l0068), 1) & Right$(Str$(l006C), 1) & " " & l0074
l0082 = Int(Rnd * 38)
Select Case l0082
Case 0: Text1 = "Oscar"
Case 1: Text1 = "Jimmy"
Case 2: Text1 = "Patricia"
Case 3: Text1 = "Harold"
Case 4: Text1 = "Ruth"
Case 5: Text1 = "Samuel"
Case 6: Text1 = "Adam"
Case 7: Text1 = "Brian"
Case 8: Text1 = "Zachary"
Case 9: Text1 = "Samantha"
Case 10: Text1 = "Julia"
Case 11: Text1 = "Chris"
Case 12: Text1 = "Richard"
Case 13: Text1 = "Ben"
Case 14: Text1 = "Thomas"
Case 15: Text1 = "Penelope"
Case 16: Text1 = "Justin"
Case 17: Text1 = "Bob"
Case 18: Text1 = "Jake"
Case 19: Text1 = "Frank"
Case 20: Text1 = "Amanda"
Case 21: Text1 = "Fletcher"
Case 22: Text1 = "Michael"
Case 23: Text1 = "Schroeder"
Case 24: Text1 = "Ken"
Case 25: Text1 = "Clarissa"
Case 26: Text1 = "Donna"
Case 27: Text1 = "Johnathon"
Case 28: Text1 = "Leonard"
Case 29: Text1 = "Harold"
Case 30: Text1 = "Mickey"
Case 31: Text1 = "Nathan"
Case 32: Text1 = "Kelly"
Case 33: Text1 = "Angela"
Case 34: Text1 = "Steve"
Case 35: Text1 = "Scott"
Case 36: Text1 = "Brett"
Case 37: Text1 = "Jared"
Case 38: Text1 = "William"
End Select
l008C = Int(Rnd * 40)
Select Case l008C
Case 0: Text2 = "Crotty"
Case 1: Text2 = "Crow"
Case 2: Text2 = "Evans"
Case 3: Text2 = "Dudley"
Case 4: Text2 = "Everest"
Case 5: Text2 = "Finney"
Case 6: Text2 = "Nelson"
Case 7: Text2 = "Fitts"
Case 8: Text2 = "Gallaway"
Case 9: Text2 = "Hanks"
Case 10: Text2 = "Hammond"
Case 11: Text2 = "Jackson"
Case 12: Text2 = "Smith"
Case 13: Text2 = "Johson"
Case 14: Text2 = "Garrets"
Case 15: Text2 = "Collahan"
Case 16: Text2 = "Lambert"
Case 17: Text2 = "McGuire"
Case 18: Text2 = "Newton"
Case 19: Text2 = "Ngyuen"
Case 20: Text2 = "Leon"
Case 21: Text2 = "Newkirk"
Case 22: Text2 = "Parry"
Case 23: Text2 = "Pardo"
Case 24: Text2 = "Regan"
Case 25: Text2 = "Sloan"
Case 26: Text2 = "Flemings"
Case 27: Text2 = "Klavik"
Case 28: Text2 = "Stiener"
Case 29: Text2 = "Thole"
Case 30: Text2 = "Wesson"
Case 31: Text2 = "Tandy"
Case 32: Text2 = "Slay"
Case 33: Text2 = "Rodriguez"
Case 34: Text2 = "Piland"
Case 35: Text2 = "Norwood"
Case 36: Text2 = "Mosley"
Case 37: Text2 = "Lamooney"
Case 38: Text2 = "Keeler"
Case 39: Text2 = "Herron"
Case 40: Text2 = "Hiebert"
End Select
L49AC:
Text6.Text = ""
Text7.Text = ""
l00A2 = 1
Randomize
l00A6 = 4019
l00AA = "Bank Of America"
Text7.Text = l00AA
For l00C4 = 1 To 12
L4A3C:
    For l00C8 = 1 To 16
    m00AE(l00C8) = 0
    Next l00C8
         Randomize
        l00CC = 1000 + Rnd * 999
        l00D0 = Rnd * 9999
        l00D4 = Rnd * 9999
         l00D8 = Int(l00CC)
         l00DC = Int(l00D0)
         l00E0 = Int(l00D4)
            l00E4 = l00D8 \ 1000
            l00E8 = l00E4 * 1000
            m00AE(1) = l00E4
            l00EC = l00D8 - l00E8
            l00F0 = l00EC \ 100
            l00F4 = l00F0 * 100
            m00AE(2) = l00F0
            l00F8 = l00EC - l00F4
            l00FC = l00F8 \ 10
            l0100 = l00FC * 10
            m00AE(3) = l00FC
            l0104 = l00F8 - l0100
            m00AE(4) = l0104
            l0108 = l00DC \ 1000
            l010C = l0108 * 1000
            m00AE(5) = l0108
            l0110 = l00DC - l010C
            l0114 = l0110 \ 100
            l0118 = l0114 * 100
            m00AE(6) = l0114
            l011C = l0110 - l0118
            l0120 = l011C \ 10
            l0124 = l0120 * 10
            m00AE(7) = l0120
            l0128 = l011C - l0124
            m00AE(8) = l0128
            l012C = l00E0 \ 1000
            l0130 = l012C * 1000
            m00AE(9) = l012C
            l0134 = l00E0 - l0130
            l0138 = l0134 \ 100
            l013C = l0138 * 100
            m00AE(10) = l0138
            l0140 = l0134 - l013C
            l0144 = l0140 \ 10
            l0148 = l0144 * 10
            m00AE(11) = l0144
            l014C = l0140 - l0148
            m00AE(12) = l014C
            l0150 = l00A6 \ 1000
            l0154 = l0150 * 1000
            m00AE(13) = l0150
            l0158 = l00A6 - l0154
            l015C = l0158 \ 100
            l0160 = l015C * 100
            m00AE(14) = l015C
            l0164 = l0158 - l0160
            l0168 = l0164 \ 10
            l016C = l0168 * 10
            m00AE(15) = l0168
            l0170 = l0164 - l016C
            m00AE(16) = l0170
         For l0174 = 1 To 15 Step 2
           m00AE(l0174) = m00AE(l0174) * 2
           If  m00AE(l0174) > 9 Then
           m00AE(l0174) = m00AE(l0174) - 9
           End If
         Next l0174
            l0178 = 0
           For l017C = 1 To 16
           l0178 = l0178 + m00AE(l017C)
           Next l017C
           l0180 = l0178
           l0184 = l0180 \ 10
           l0188 = l0184 * 10
           l018C = l0180 - l0188
          If  l018C = 0 Then
      l0190 = Str$(l00A6)
      l0074 = Str$(l00D8)
      l0194 = Str$(l00DC)
      l0198 = Str$(l00E0)
        l019C = Str$(l00A2)
        Text6 = Right$((l0190 & "-" & Format$(l0074, "0###") & "-" & Format$(l0194, "0###") & "-" & Format$(l0198, "0###")), 19)
End If
Next l00C4
If  Text6.Text = "" Then GoTo L49AC
End Sub

Sub Command3D2_Click ()
Dim l01AA As Variant
Dim l01AE As Variant
Dim l01B4 As Variant
Dim l01BE As String
Dim l01C6 As String
Dim l01CE As Variant
Dim l01D4 As Variant
Dim l01D8 As String
Dim l01DA As String
Dim l01DC As String
Dim l01DE As String
Dim l01E0 As String
Dim l01E2 As String
Dim l01E4 As String
Dim l01E6 As Variant
Dim l01EC As Variant
Dim l01F0 As Variant
Dim l01F4 As String
Dim l01F6 As String
Dim l01F8 As String
Dim l0200 As Variant
' Const c0208 =-1 ' &HFFFF%
' Const c020A = 3 ' &H3%
If  Text1 = "" Then Command3D1_Click
Fakes.Hide
Creating.Show
l01AA = extfn3078("AOL Frame25", "America  Online")
l01AE = extfn3078("_AOL_Modal", 0&)
If  l01AE = 0 Then MsgBox "Sign on to AOL as New User first, dumbass!", 16: Creating.Hide: Fakes.Show: Exit Sub
l01B4 = extfnC8(l01AE, "_AOL_Edit")
l01BE$ = Text11
l01C6$ = Text12
Clipboard.SetText l01C6$
l01CE = extfn1478(l01B4)
SendKeys l01BE$
SendKeys "{TAB}^v~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
Creating.Panel3D1.Caption = "  Skipping past idiot instructions..."
l01D4 = extfn3078("_AOL_Modal", 0&)
If  l01D4 = l01AE Or l01D4 = 0 Then
  sub4210 (1)
  l01D4 = extfn3078("_AOL_Modal", 0&)
  If  l01D4 = l01AE Or l01D4 = 0 Then
    sub4210 (3)
    l01D4 = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01CE = extfn1478(l01D4)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
Creating.Panel3D1.Caption = "  Entering name, address, and phone #..."
l01AE = extfn3078("_AOL_Modal", 0&)
If  l01AE = l01D4 Or l01AE = 0 Then
  sub4210 (1)
  l01AE = extfn3078("_AOL_Modal", 0&)
  If  l01AE = l01D4 Or l01AE = 0 Then
    sub4210 (3)
    l01AE = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01AE = extfn3078("_AOL_Modal", 0&)
l01D8$ = Text1
l01DA$ = Text2
l01DC$ = Text3
l01DE$ = Text10
l01E0$ = Text5
l01E2$ = Text9
l01E4$ = Text4
l01B4 = extfnC8(l01AE, "_AOL_Edit")
l01E6 = extfn1478(l01B4)
SendKeys l01D8$ + "{TAB}" + l01DA$ + "{TAB}" + l01DC$ + "{TAB}"
SendKeys l01DE$ + "{TAB}" + l01E0$ + "{TAB}"
SendKeys l01E2$ + "{TAB}{TAB}" + l01E4$
SendKeys "{TAB}" + l01E4$ + "~"
Creating.Panel3D1.Caption = "  Skipping past billing bullshit..."
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
l01D4 = extfn3078("_AOL_Modal", 0&)
If  l01D4 = l01AE Or l01D4 = 0 Then
  sub4210 (1)
  l01D4 = extfn3078("_AOL_Modal", 0&)
  If  l01D4 = l01AE Or l01D4 = 0 Then
    sub4210 (3)
    l01D4 = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01D4 = extfn3078("_AOL_Modal", 0&)
l01CE = extfn1478(l01D4)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
l01AE = extfn3078("_AOL_Modal", 0&)
If  l01AE = l01D4 Or l01AE = 0 Then
  sub4210 (1)
  l01AE = extfn3078("_AOL_Modal", 0&)
  If  l01AE = l01D4 Or l01AE = 0 Then
    sub4210 (3)
    l01AE = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01AE = extfn3078("_AOL_Modal", 0&)
l01EC = extfn100(l01AE, "Continue")
l01CE = extfn1478(l01EC)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
Creating.Panel3D1.Caption = "  Selecting billing method..."
l01F0 = extfn100(l01AA, "Select")
If  l01F0 = 0 Then
  sub4210 (1)
  l01F0 = extfn100(l01AA, "Select")
  If  l01F0 = 0 Then
    sub4210 (3)
  End If
End If
l01F4$ = Text6
l01F6$ = Text8
l01F8$ = "Bank Of America"
l01CE = extfn1478(l01F0)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
Creating.Panel3D1.Caption = "  Entering billing information..."
l01AE = extfn3078("_AOL_Modal", 0&)
If  l01AE = 0 Then
  sub4210 (2)
  l01AE = extfn3078("_AOL_Modal", 0&)
  If  l01AE = 0 Then
    sub4210 (2)
    l01AE = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01AE = extfn3078("_AOL_Modal", 0&)
l01B4 = extfnC8(l01AE, "_AOL_Edit")
l01CE = extfn1478(l01B4)
SendKeys l01F4$ + "{TAB}" + l01F6$ + "{TAB}" + l01F8$ + "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
Creating.Panel3D1.Caption = "  Reaffirming billing information..."
l01D4 = extfn3078("_AOL_Modal", 0&)
If  l01D4 = l01AE Or l01D4 = 0 Then
  sub4210 (2)
  l01D4 = extfn3078("_AOL_Modal", 0&)
  If  l01D4 = l01AE Or l01D4 = 0 Then
    sub4210 (2)
    l01D4 = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01D4 = extfn3078("_AOL_Modal", 0&)
l01CE = extfn1478(l01D4)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
l01AE = extfn3078("_AOL_Modal", 0&)
If  l01AE = l01D4 Or l01AE = 0 Then
  sub4210 (2)
  Creating.Panel3D1.Caption = "  Lying about agreeing to TOS..."
  l01AE = extfn3078("_AOL_Modal", 0&)
  If  l01AE = l01D4 Or l01AE = 0 Then
    sub4210 (2)
    l01AE = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01AE = extfn3078("_AOL_Modal", 0&)
l01CE = extfn1478(l01AE)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
Creating.Panel3D1.Caption = "  Skipping past SN information..."
l01D4 = extfn3078("_AOL_Modal", 0&)
If  l01D4 = l01AE Or l01D4 = 0 Then
  sub4210 (2)
  l01D4 = extfn3078("_AOL_Modal", 0&)
  If  l01D4 = l01AE Or l01D4 = 0 Then
    sub4210 (2)
    l01D4 = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01D4 = extfn3078("_AOL_Modal", 0&)
l01CE = extfn1478(l01D4)
SendKeys "~"
sub4210 (3)
DoEvents
If  gv0072 = 1 Then Creating.Hide: Fakes.Show: gv0072 = 0: Exit Sub
l01AE = extfn3078("_AOL_Modal", 0&)
If  l01AE = l01D4 Or l01AE = 0 Then
  sub4210 (2)
  l01AE = extfn3078("_AOL_Modal", 0&)
  If  l01AE = l01D4 Or l01AE = 0 Then
    sub4210 (2)
    l01AE = extfn3078("_AOL_Modal", 0&)
  End If
End If
l01AE = extfn3078("_AOL_Modal", 0&)
l01CE = extfn1478(l01AE)
SendKeys "~"
sub4210 (1)
Creating.Panel3D1.Caption = "  Complete! Choose SN and password!"
sub4210 (2)
l0200 = extfn170(App.Path + "\created.wav", 1)
Unload Creating
Unload Me
End Sub

Sub Command3D3_Click ()
Unload Me
End Sub

Sub Command3D4_Click ()
ResetSN.Show
End Sub


Sub Form_Load ()
Dim l020E As Variant
Dim l0212 As Variant
l020E = extfn4120(Fakes.hWnd, c0208, 0, 0, 0, 0, c020A)
Fakes.Left = 0
Fakes.Top = 0
l0212 = "19-4236-8512 HASTED-SOCK"
l0212 = "20-5271-4002 VOTE-VISCID"
l0212 = "19-5443-6841 ADVERB-AFRAID"
Text11 = "19-4236-8512"
Text12 = "HASTED-SOCK"
End Sub

Sub Form_Unload (p1 As Integer)
Phisher.Show
End Sub
