' ICAIZIT.FRM
Option Explicit

Sub Command1_Click ()
If  Text1.Text = "" Then MsgBox "Type in Da String!", 16, "Error": Exit Sub
If  UCase$(Text1.Text) = UCase$("alphazulu136420") Then
MsgBox "Thats YuBaN!!!", 77, "YippY!"
Call subBF0("†     ïñ^v[§A.T.T.E.N.T.I.O.N§]v^ñï")
subD08 1E-100#
Call subBF0("ïñ^v[§YuﬂaN is Online Right Now!§]v^ñï")
subD08 1E-100#
Call subBF0("ïñ^v[§Oh My God!..I Gotta Go Suck on his Dick§]v^ñï")
subD08 1E-100#
Call subBF0("†     ïñ^v[§A.T.T.E.N.T.I.O.N§]v^ñï")
subD08 1E-100#
subD08 .3#
Unload Me
Else
MsgBox "Wrong!", 16, "TOS THAT POZER ASS!!!"
End If
End Sub

Sub Command2_Click ()
Unload Me
End Sub

Sub Form_Load ()
subCD0 Me
End Sub
