' COLORS.FRM
Option Explicit

Sub Form_Load ()
Picture1.BackColor = QBColor(0)
Picture2.BackColor = QBColor(1)
Picture3.BackColor = QBColor(2)
Picture4.BackColor = QBColor(3)
Picture5.BackColor = QBColor(4)
Picture6.BackColor = QBColor(5)
Picture7.BackColor = QBColor(6)
Picture8.BackColor = QBColor(7)
Picture9.BackColor = QBColor(8)
Picture10.BackColor = QBColor(9)
Picture11.BackColor = QBColor(10)
Picture12.BackColor = QBColor(11)
Picture13.BackColor = QBColor(12)
Picture14.BackColor = QBColor(13)
Picture15.BackColor = QBColor(14)
Picture16.BackColor = QBColor(15)
extsub1050 colors.hWnd, -1, 0, 0, 0, 0, 3
End Sub

Sub Picture1_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(0)
Else
drawman.Text1.BackColor = QBColor(0)
End If
End Sub

Sub Picture10_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(9)
Else
drawman.Text1.BackColor = QBColor(9)
End If
End Sub

Sub Picture11_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(10)
Else
drawman.Text1.BackColor = QBColor(10)
End If
End Sub

Sub Picture12_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(11)
Else
drawman.Text1.BackColor = QBColor(11)
End If
End Sub

Sub Picture13_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(12)
Else
drawman.Text1.BackColor = QBColor(12)
End If
End Sub

Sub Picture14_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(13)
Else
drawman.Text1.BackColor = QBColor(13)
End If
End Sub

Sub Picture15_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(14)
Else
drawman.Text1.BackColor = QBColor(14)
End If
End Sub

Sub Picture16_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(15)
Else
drawman.Text1.BackColor = QBColor(15)
End If
End Sub

Sub Picture2_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(1)
Else
drawman.Text1.BackColor = QBColor(1)
End If
End Sub

Sub Picture3_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(2)
Else
drawman.Text1.BackColor = QBColor(2)
End If
End Sub

Sub Picture4_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(3)
Else
drawman.Text1.BackColor = QBColor(3)
End If
End Sub

Sub Picture5_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(4)
Else
drawman.Text1.BackColor = QBColor(4)
End If
End Sub

Sub Picture6_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(5)
Else
drawman.Text1.BackColor = QBColor(5)
End If
End Sub

Sub Picture7_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(6)
Else
drawman.Text1.BackColor = QBColor(6)
End If
End Sub

Sub Picture8_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(7)
Else
drawman.Text1.BackColor = QBColor(7)
End If
End Sub

Sub Picture9_Click ()
If  colors.Caption = "ForeColor Selection" Then
drawman.Text1.ForeColor = QBColor(8)
Else
drawman.Text1.BackColor = QBColor(8)
End If
End Sub
