' CREDITS.FRM
Option Explicit

Sub sub99F8 ()
End Sub

Sub Form_Load ()
extsub1050 credits.hWnd, -1, 0, 0, 0, 0, 3
Timer1.Interval = 1
End Sub

Sub Timer1_Timer ()
Dim l0026 As Variant
Dim l002C As Variant
l0026 = extfn1210("Channlx.wav", 1)
l002C = fn13A0(1)
sub250
Label1.Caption = "LooNi"
Label2.Caption = "LooNi"
l002C = fn13A0(1)
sub250
Label1.Caption = "HaVoK"
Label2.Caption = "HaVoK"
l002C = fn13A0(1)
sub250
Label1.Caption = "DEXTRIN"
Label2.Caption = "DEXTRIN"
l002C = fn13A0(1)
sub250
Label1.Caption = "Iodine NT"
Label2.Caption = "Iodine NT"
l002C = fn13A0(1)
sub250
Label1.Caption = "Dobi"
Label2.Caption = "Dobi"
l002C = fn13A0(1)
sub250
Label1.Caption = "AsTrO"
Label2.Caption = "AsTrO"
l002C = fn13A0(1)
sub250
Label1.Caption = "Drunkkyd"
Label2.Caption = "Drunkkyd"
l002C = fn13A0(1)
sub250
Label1.Caption = "WizarD"
Label2.Caption = "WizarD"
l002C = fn13A0(1)
sub250
Label1.Caption = "IrOnNuT7"
Label2.Caption = "IrOnNuT7"
l002C = fn13A0(1)
sub250
Label1.Caption = "FaMBaM"
Label2.Caption = "FaMBaM"
l002C = fn13A0(1)
sub250
Label1.Caption = "LwMxVice"
Label2.Caption = "LwMxVice"
l002C = fn13A0(1)
sub250
Label1.Caption = "PRiMaL"
Label2.Caption = "PRiMaL"
l002C = fn13A0(1)
sub250
Label1.Caption = "XaBaRaS"
Label2.Caption = "XaBaRaS"
l002C = fn13A0(1)
sub250
Label1.Caption = "O\\'D"
Label2.Caption = "O\\'D"
l002C = fn13A0(1)
sub250
Timer1.Interval = 0
Unload credits
End Sub
