' LAMERIZE.FRM
Option Explicit

Sub Command3D1_Click ()
Dim l001C As Variant
Dim l0020 As Variant
Dim l002A As Variant
DoEvents
l001C = fnA30("–¤––• Fate Ultra (\/\ass /\/)ailer By MaGuS •––¤–")
DoEvents
l0020 = fnA30("–¤––• The (\/\ /\/) is going out in (20) mins. •––¤–")
DoEvents
l002A = fnA30("–¤––• Type """ + Text1.Text + """ To get on •––¤–")
DoEvents
End Sub

Sub Form_Load ()
extsub1050 lamerizer.hWnd, -1, 0, 0, 0, 0, 3
End Sub
