<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage Express 2.0">
<title>JMR32.bas</title>
</head>

<body bgcolor="#FFFFFF" link="#808080" vlink="#808080"
alink="#C0C0C0" bgproperties="fixed">

<p align="center"><font color="#808080" size="2" face="Arial"><strong><u><img
src="JMR32.jpg" width="400" height="200"></u></strong></font></p>

<p><font color="#808080" size="2" face="Arial"><strong><u>Description:</u></strong></font><font
size="2" face="Arial"> This is version 1 of JMR32.bas. It took me
only a few hours to assemble this, and some of the subs, and
functions werent tested within in that time. So don't get mad if
something doesn't work, or because there isn't that much in here.
Over all it has the basic subs, and functions to make a pretty
good prog.<br>
<br>
</font><font color="#808080" size="2" face="Arial"><strong><u>Codes:</u></strong></font><font
size="2" face="Arial"><br>
How to the Chat_Buddy Sub:<br>
Chat_Buddy &quot;Someones SN here&quot;, &quot;The Room
here&quot;<br>
<br>
How to use the IM_Send Sub:<br>
IM_Send &quot;Person to send to&quot;, &quot;Your Message&quot;<br>
<br>
How to make a form stay on top:<br>
Window_OnTop </font><font color="#000080" size="2" face="Arial">Me</font><font
size="2" face="Arial">.hwnd<br>
<br>
How to make a form from not staying on top:<br>
Window_NotOnTop </font><font color="#000080" size="2"
face="Arial">Me</font><font size="2" face="Arial">.hwnd<br>
<br>
How to print using the VBPrint Sub:<br>
VBPrint &quot;What you want to print here&quot;, &quot;12&quot;,
&quot;Arial&quot;, </font><font color="#000080" size="2"
face="Arial">False</font><font size="2" face="Arial">, </font><font
color="#000080" size="2" face="Arial">False</font><font size="2"
face="Arial">, </font><font color="#000080" size="2" face="Arial">False</font><font
size="2" face="Arial">, </font><font color="#000080" size="2"
face="Arial">False</font></p>

<p align="center"><font color="#000000" size="1" face="Arial">All
codes posted are not ALL the codes available in the world, just
some simple ones for newbies.</font></p>
</body>
</html>
